version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "mix"
    directory: "/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/web/assets"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/macos"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
