[package]
name = "decant-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
blake3 = "1.8.5"
directories = "6.0.0"
rayon = "1.12.0"
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3"
